.github/workflows/selftest.yml
README.md
action.py
test/artifact1.txt
test/artifact2.txt

action.py: Support file globbing for inputs

---

README.md
action.py
action.yml

Remove output prefix from `output-{certificate, signature}` settings

---

action.py

action.py: fix summary formatting

---

action.py
templates/sigstore-python-sign.md
templates/sigstore-python-verify.md

action, templates: add and render summaries with templates

---

.github/workflows/selftest.yml
README.md
action.py
action.yml

Streamline settings

---

action.py

This duplicates `_SUMMARY` above.

action.py: Remove unused line

---

README.md
requirements.txt

README: prep for 0.0.8

---

.github/workflows/selftest.yml
README.md
action.py
action.yml
setup/setup.bash

Complete migration to sigstore org

---

.github/workflows/selftest.yml

selftest: restrict to non-PRs and PRs on non-forks

---

.github/workflows/selftest.yml

workflows/selftest: add more xfail selftests

---

.github/workflows/selftest.yml
README.md
action.py
action.yml
requirements.txt

Bundle support

---

README.md

README: prep 1.1.0

---

.github/workflows/selftest.yml

selftest: skip alls-green if 3p PR

---

action.py

action: stringify `file_`

---

README.md

README: prep 1.2.2

---

README.md

Prep 1.2.3

---

.github/workflows/ci.yml
.github/workflows/selftest.yml
action.py
action.yml

Runs the selftest CI on Windows as well, to keep us from regressing going forwards.
Closes #71.

action: accommodate Windows

---

README.md

README: prep 2.0.1

---

README.md

README: prep 2.1.0

---

requirements.txt

requirements: pin sigstore-rekor-types subdep

---

README.md

Closes https://github.com/sigstore/gh-action-sigstore-python/issues/153
All examples should use the same version (v3.0.0).
NONE
N/A

Fix remaining reference to 2.1.1 in README

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/selftest.yml
.github/workflows/semgrep.yml
.github/workflows/zizmor.yml

Fixes a bunch of mostly-low zizmor findings, cleans things up slightly, adds a zizmor workflow.

ci: cleanup, fix zizmor findings
