sigstore/gh-action-sigstore-python

README.md
I noticed that I forgot to make a note of this. This permission needs to be set in any workflow that uses the Action.
=> README: Add note about OIDC workflow permissions

README.md, action.yml
This more accurately reflects the release lifecycle.
=> Use "release published" as our release event for asset uploading

.github/workflows/release.yml
This effectively serves as another self-test, by ensuring that we attach signing artifacts to releases correctly.
=> workflows/release: add a release workflow

.github/workflows/selftest.yml
=> Add more self tests to CI

requirements.txt
Remove obsolete transitive constraint.
=> requirements: sigstore==0.6.5

README.md
Seems like this was renamed or pushed into a different org, which was confusion going through the text. Updated all references to fix this.
Fixes #28 
Signed-off-by: Rob Bos rajbos@users.noreply.github.com
Prevent confusion for users reading the README, since that refers to a different owner then where the repo currently is.
NONE
=> Update references to `trailofbits` to `sigstore` to avoid confusion

.github/workflows/selftest.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Signed-off-by: Bob Callaway <bcallaway@google.com>
=> chore: fix deprecated set-output

.github/workflows/selftest.yml, README.md, action.py, requirements.txt
Now that we have a stable release of `sigstore-python`, we should also do a stable release here,
=> Prep 1.0.0

README.md, action.py, action.yml, requirements.txt
This PR resolves #44. We now do the following on releases if `release-signing-artifacts` is enabled:
1. Download the default release artifacts, i.e.`{{ref}}.tar.gz` and `{{ref}}.zip`;
2. Sign for them;
3. Upload them back to the release as `{{ref}}-signed.{{extension}}`, along with their signatures.
The `release-signing-artifacts` setting was extended to re-upload and sign default assets. Previously, the stability of default asset hashes were not guaranteed, as they are generated on-the-fly by GitHub.
https://docs.sigstore.dev does not seem to include documentation on the actions, but I will add a commit documenting the change to `release-signing-artifacts` in this repo's README.
=> action: download default release assets to sign

.github/workflows/release.yml, README.md, action.py, action.yml
This changeset resolves #47 by adding the `bundle-only` setting, which disables the upload of `.crt` and `.sig` outputs.
Implemented the `bundle-only` setting, which disables upload of `.crt` and `.sig` artifacts when used in conjunction
with `upload-signing-artifacts` and `release-signing-artifacts`.
Documented in the README!
=> action: implement and document `bundle-only`

README.md, action.py
Fixes the handling of suffixes; the previous use of `with_suffix` would mangle the artifact names if they contained anything that looked like a suffix (e.g. a minor version).
=> Bugfix, prep 1.2.1

.github/workflows/selftest.yml, action.py
Resolves #54.
The action now uploads the original artifacts from `inputs` alongside their signatures.
=> action: upload artifact being signed for

action.py
#55 introduced a regression that attempts to upload release artifacts twice:
https://github.com/sigstore/gh-action-sigstore-python/actions/runs/4509743983/jobs/7943593657#step:3:238
We fix this by not adding the release artifact explicitly to `signing_artifact_paths` in the release artifact special case.
=> action: deduplicate release artifact upload

.github/workflows/release.yml, .github/workflows/selftest.yml, README.md, action.py, action.yml
=> action, selftest: deprecate `bundle-only: false`

action.py, requirements.txt
Fixes #62.
cc @MatthiasValvekens
=> action: handle slashes in ref names

.github/workflows/schedule-selftest.yml, .github/workflows/selftest.yml
Mostly cribbed from [`sigstore-python`](https://github.com/sigstore/sigstore-python/blob/e1ed0bbbe4530509882f8bc4a54e3ce4f82beca2/.github/workflows/staging-tests.yml).
Resolves #64.
=> `schedule-selftest.yml` workflow

.github/workflows/selftest.yml, action.yml, setup/setup.bash
This enables debugging in our self-tests, and ensures that we print out the Python and pip versions while debugging.
=> feat: more debugging, version printing

requirements.txt
Bumps our use of sigstore-python to 2.0.
~~We only have prereleases out at the moment, so this should resolve to the latest one (until we make a stable release).~~
=> requirements: sigstore ~= 2.0

requirements.txt, setup/setup.bash
Seals off the resolution bug we saw in #94.
I'll do a release after this.
=> requirements: bump sigstore-python

.github/workflows/selftest.yml, README.md, action.py
This has two parts:
* We now silently ignore `release-signing-artifacts` if the `GITHUB_EVENT_NAME` is not `release`, since it can only work in the context of releases and their associated artifacts.
* The documentation for `release-signing-artifacts` now makes this clear.
CC @stevenh for review as well, as the original reporter 🙂 
Closes #99.
=> Fix `release-signing-artifacts` behavior and docs

.github/workflows/selftest.yml, README.md, action.py, test/more white space.txt, test/white space.txt
Makes `inputs` slightly more uniform. Needs self-tests.
Closes #77.
=> action: use shlex.split

.github/workflows/schedule-selftest.yml
This is a known persistent performance issue with staging; most people don't need to be nagged about it.
=> schedule-selftest: reduce nagging

.github/workflows/selftest.yml, action.py, action.yml, setup/setup.bash
=> action: use a venv to prevent PEP 668 errors

README.md, action.yml
This was another pre-3.0 task.
Closes #45.
=> action: flip `release-signing-artifacts`

.github/workflows/release.yml, .github/workflows/selftest.yml
* remove unnecessary action argument in release workflow
* remove selftest that is now essentially a duplicate of previous test
=> Cleanup workflows

CHANGELOG.md, README.md
~~Blocked on #142 and other lingering 3.0 tasks.~~
=> Prep 3.0.0

action.py, setup/setup.bash
ACTIONS_STEP_DEBUG is a standard GitHub Actions flag to enable debugging output across all actions and workflows.
See: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Supersedes: https://github.com/sigstore/gh-action-sigstore-python/pull/150
FIX: debugging output is now enabled also with the standard `ACTIONS_STEP_DEBUG==true` environment variable.
NONE
=> Enable debugging also if ACTIONS_STEP_DEBUG==true

CHANGELOG.md, requirements.txt, setup/setup.bash
sigstore >= 3.4 requires 3.9, so this action does as well.
=> setup, requirements: bump to Python 3.9

README.md
Addresses #162 . 
Links to new CI Quickstart and mentions that the github action can be used by non-python projects too. 
None
None
=> Linking to CI Quickstart and clarifying that action can be used for non-python projects
